### ISSUE TITLE
Seems Microsoft changed something, Only single IP can be sync to the MDATP.

### ISSUE THREAD

**Issue by banhao** [PaloAltoNetworks/minemeld-wd-atp#6]
https://live.paloaltonetworks.com/t5/minemeld-discussions/system-engine-logs-cidr-is-not-a-valid-ip-indicator-error/td-p/354131
Can you update the prototype to only output single IPs?

**Comment by fvigo** [comment]
Thanks @banhao , will check with Microsoft and figure out what to do.

**Comment by fvigo** [comment]
Confirmed with Microsoft that their API doesn't accept CIDRs anymore.

Resolved in : #8

**Comment by fvigo** [comment]
@banhao we have released version 0.5 that should address this problem. We couldn't test it ourselves against a real ATP tenant: would you please test it when you have a chance and report back if everything works?

thanks a lot!

**Comment by banhao** [comment]
@fvigo, seem it doesn't work. 
node.py line#664 I changed it to "r = netaddr.IPRange(a1, a2)" then it worked.
I only update the node.py, minemeld.json that 2 files and compile the "node.py" to "node.pyc" by using "python -m py_compile node.py"

**Comment by fvigo** [comment]
Thanks, it's OK now!
